Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.4"

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true  # brings up the vm in gui window
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.network "private_network", type: "dhcp"

  # config.vm.provision "shell", path: "provision.sh"
  
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "python"
  end
end
